#!/usr/bin/env node
'use strict'

const path = require('node:path')
const fs = require('node:fs/promises')
const pkg = require('../package.json')

const info = {release_date: new Date().toISOString(), version: pkg.version}
const location = path.join(__dirname, '..', 'release.info')
const content = JSON.stringify(info, null, 2)
console.log('writing version info %s %j', location, info)
fs.writeFile(location, content)
